### ISSUE TITLE
WTB rich(-er) ASSERTS

### ISSUE THREAD

**Issue by anporumb** [Azure/azure-ctest#13]
At the moment the following is possible
```c
CTEST_ASSERT_IS_TRUE_WITH_MSG(3==3, "someMessage").
```

I would like to have the MSG part extended, to behave printf-ish like, as in:
CTEST_ASSERT_IS_TRUE_WITH_MSG(3==3, "here is my integer = %d", i);

**Comment by dcristoloveanu** [comment]
This is done.
